baseURL = 'https://www.plaintext.recipes/'
languageCode = 'en-us'
title = 'Plaintext Recipes'
theme = "smol"

# Parameters
[params]
    subtitle = "A website serving plain text, but umami recipes >:)"
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/austinorth/plaintext-recipes"
        weight = 1

    [[menu.footer]]
        name = "Twitter"
        url = "https://twitter.com/HumbleBroski"
        weight = 2

    [[menu.footer]]
        name = "Personal Site"
        url = "https://austinorth.com"
        weight = 3

